version: '3.8'

services:
  app:
    build: .
    container_name: contactmanager_app
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - ./src:/app/src
      - ./prisma:/app/prisma
    restart: unless-stopped

  db:
    image: postgres:15
    container_name: contactmanager_db
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
